#!/bin/bash
# Generate a shared JWT secret and write it to both backend/.env and
# collab-server/.env so the Python backend can verify tokens issued by the
# collab server. Safe to re-run — it reuses an existing secret when one of
# the two .env files already has it.

set -euo pipefail

cd "$(dirname "$0")"

BACKEND_ENV="backend/.env"
COLLAB_ENV="collab-server/.env"
BACKEND_ENV_EXAMPLE="backend/.env.example"
COLLAB_ENV_EXAMPLE="collab-server/.env.example"

# ── Extract an existing secret, if any, from either file ──────────────────
existing_secret=""
for f in "$COLLAB_ENV" "$BACKEND_ENV"; do
  if [[ -f "$f" ]]; then
    s="$(grep -E '^(JWT_SECRET|COLLAB_JWT_SECRET)=' "$f" | head -1 | cut -d= -f2- || true)"
    if [[ -n "$s" ]]; then
      existing_secret="$s"
      break
    fi
  fi
done

if [[ -z "$existing_secret" ]]; then
  # 64 hex chars = 32 bytes of entropy
  existing_secret="$(openssl rand -hex 32)"
  echo "Generated new shared JWT secret."
else
  echo "Reusing existing JWT secret from ${f}."
fi

# ── Resolve data paths ────────────────────────────────────────────────────
# Collab SQLite lives under collab-server/data by default; the backend reads
# it in read-only mode to look up the authenticated user.
COLLAB_DB_PATH="$(cd collab-server && pwd)/data/collab.sqlite3"
COLLAB_SERVER_URL="http://localhost:4000"
APP_URL="http://localhost:5173"

# ── Write backend/.env ────────────────────────────────────────────────────
if [[ ! -f "$BACKEND_ENV" ]]; then
  cat > "$BACKEND_ENV" <<EOF
# Auto-generated by setup_auth_env.sh — do not commit.
# The backend validates JWTs issued by the collab server using this shared
# HS256 secret. Keep both sides identical or logins will return 401.
COLLAB_JWT_SECRET=${existing_secret}

# Path to the collab server's SQLite users file (read-only from here).
COLLAB_DB_PATH=${COLLAB_DB_PATH}

# Where the backend proxies /api/auth/* requests.
COLLAB_SERVER_URL=${COLLAB_SERVER_URL}

# Free-plan quota — scripts per user before /api/scripts returns 402.
FREE_PLAN_FILE_LIMIT=5

# Set to 1 to show the demo banner + warnings in CollabLoginDialog.
# DEMO_MODE=1
EOF
  echo "Wrote ${BACKEND_ENV}"
else
  echo "${BACKEND_ENV} already exists — not overwriting. Ensure COLLAB_JWT_SECRET matches collab's JWT_SECRET."
fi

# ── Write collab-server/.env ──────────────────────────────────────────────
if [[ ! -f "$COLLAB_ENV" ]]; then
  cat > "$COLLAB_ENV" <<EOF
# Auto-generated by setup_auth_env.sh — do not commit.
JWT_SECRET=${existing_secret}

# Magic-link URLs in verification emails resolve against this base URL.
APP_URL=${APP_URL}

# SMTP is optional — when unset, the verification code is printed to stdout
# and the account auto-verifies. Set these to send real emails.
# SMTP_HOST=smtp.example.com
# SMTP_PORT=587
# SMTP_USER=
# SMTP_PASS=
# SMTP_FROM=noreply@opendraft.app

# Google OAuth (optional).
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
EOF
  echo "Wrote ${COLLAB_ENV}"
else
  echo "${COLLAB_ENV} already exists — not overwriting. Ensure JWT_SECRET matches backend's COLLAB_JWT_SECRET."
fi

# ── Write .env.example siblings ───────────────────────────────────────────
cat > "$BACKEND_ENV_EXAMPLE" <<'EOF'
# Copy to backend/.env (or run ./setup_auth_env.sh to create it automatically).
COLLAB_JWT_SECRET=change-me-to-a-long-random-string-matching-collab
COLLAB_DB_PATH=/absolute/path/to/collab-server/data/collab.sqlite3
COLLAB_SERVER_URL=http://localhost:4000
FREE_PLAN_FILE_LIMIT=5
# DEMO_MODE=1
EOF

cat > "$COLLAB_ENV_EXAMPLE" <<'EOF'
# Copy to collab-server/.env (or run ./setup_auth_env.sh to create it automatically).
# Must match backend's COLLAB_JWT_SECRET.
JWT_SECRET=change-me-to-a-long-random-string-matching-backend
APP_URL=http://localhost:5173
# SMTP_HOST=smtp.example.com
# SMTP_PORT=587
# SMTP_USER=
# SMTP_PASS=
# SMTP_FROM=noreply@opendraft.app
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
EOF

echo ""
echo "Done. Restart start_backend.sh (and the auth server, if running) to pick up the new env."
