// GENERATED by devtools/build-helper-catalog.mjs — do not edit by hand.
// The icons the helper-text catalog references, imported one by one so
// tree-shaking keeps only what the catalog actually names.
import type { IconType } from 'react-icons';
import { FaAlignCenter, FaAlignJustify, FaAlignLeft, FaAlignRight, FaArrowLeft, FaArrowsAltH, FaBars, FaBold, FaCamera, FaCheck, FaChevronDown, FaChevronUp, FaColumns, FaCopy, FaCrop, FaDownload, FaEdit, FaEllipsisV, FaExchangeAlt, FaFileAlt, FaFileExport, FaFileImport, FaFolderOpen, FaFolderPlus, FaHashtag, FaHighlighter, FaItalic, FaLink, FaListOl, FaListUl, FaLock, FaMapMarkerAlt, FaMarker, FaPaperclip, FaPlus, FaQuoteLeft, FaRedo, FaRegCheckCircle, FaRegEdit, FaRegEye, FaRegEyeSlash, FaRegFileAlt, FaRegHandPaper, FaRegImage, FaRegQuestionCircle, FaRegTrashAlt, FaRegUser, FaSave, FaStickyNote, FaStrikethrough, FaSubscript, FaSuperscript, FaTags, FaTimes, FaUnderline, FaUndo } from 'react-icons/fa';
import { LuColumns3, LuFileInput, LuRotateCcw, LuScissors, LuSearch, LuZoomIn, LuZoomOut } from 'react-icons/lu';

export const HELPER_ICONS: Record<string, IconType> = {
  FaAlignCenter, FaAlignJustify, FaAlignLeft, FaAlignRight, FaArrowLeft, FaArrowsAltH, FaBars, FaBold, FaCamera, FaCheck, FaChevronDown, FaChevronUp, FaColumns, FaCopy, FaCrop, FaDownload, FaEdit, FaEllipsisV, FaExchangeAlt, FaFileAlt, FaFileExport, FaFileImport, FaFolderOpen, FaFolderPlus, FaHashtag, FaHighlighter, FaItalic, FaLink, FaListOl, FaListUl, FaLock, FaMapMarkerAlt, FaMarker, FaPaperclip, FaPlus, FaQuoteLeft, FaRedo, FaRegCheckCircle, FaRegEdit, FaRegEye, FaRegEyeSlash, FaRegFileAlt, FaRegHandPaper, FaRegImage, FaRegQuestionCircle, FaRegTrashAlt, FaRegUser, FaSave, FaStickyNote, FaStrikethrough, FaSubscript, FaSuperscript, FaTags, FaTimes, FaUnderline, FaUndo, LuColumns3, LuFileInput, LuRotateCcw, LuScissors, LuSearch, LuZoomIn, LuZoomOut,
};
